const DEF = {
    FED: {
        title: `Final energy consumption`,
        definition: `Final energy consumption is the total energy used by each energy consumer for energy purposes. It excludes non-energy uses such as the transformation in chemicals of energy products. All the energy used for transport purposes is accounted for in the energy conumer Transport.`
    },
    FES: {
        title: `Final energy consumption  Energy product shares`,
        definition: `The share of each energy product in the final energy consumed by each energy consumer.`
    },
    FESV: {
        title: `Final energy consumption  Energy product values [energy unit]`,
        definition: `The needs of each energy product for each energy consumer.`
    },
    FEST: {
        title: `Final energy consumption  Energy product values TOTAL [energy unit]`,
        definition: `The total needs of each energy product.`
    },
    LOSSES: {
        title: `Secondary energy uses Losses [%]`,
        definition: `The losses correspond to losses in the supply of secondary energy to final energy consumer, e.g. losses in transmission and distribution grid in the case of electricity`
    },
    SES: {
        title: `Secondary energy uses`,
        definition: `Secondary energy is an energy product having been processed from primary level and that needs further conversion or transport to be delivered to final consumer`
    },
    ELMIX: {
        title: `Energy product shares for electricity generation by energy products`,
        definition: `The share of electricity according to the energy product used as primary fuel`
    },
    EFF: {
        title: `Energy product (technology) efficiency [%]`,
        definition: `The efficiency of each electricity generation technology, i.e. the amount of electricity at output divided by energy in input of the technology. Please note that the default efficiencies for wind, sol and hydro are 100% and for geothermal 10% as defined by IRES.`
    },
    RC: {
        title: `Reserve Capacity [ %]`,
        definition: `Reserve Capacity is the capacity needed on top of the capacity needed calculated by ESST to ensure the supply of electricity. This reserve may be used as back-up of intermittent sources.`
    },
    CC: {
        title: `Carbon cost`,
        definition: `CO2 cost corresponds to the cost of emitting 1 ton of CO2.`
    },
    DR: {
        title: `Discount rate`,
        definition: `Discount rate is used in the calculation of levelized cost of electricity.`
    },
    SESV: {
        title: `Secondary energy uses Values`,
        definition: `Electricity generated by energy source.`
    },
    PD: {
        title: `Primary production`,
        definition: `The historical or expected local extraction of energy products.`
    },
    TPES: {
        title: `Total primary energy supply`,
        definition: `Total primary energy supply is the total amount needed of each energy product to supply final energy consumption, taking into account the energy needed in the secondary level for electricity generation.`
    },
    PEEG: {
        title: `Primary energy for electricity generation`,
        definition: `The amount of energy products needed for electricity generation.`
    },
    TECH: {
        title: `Technology, environment and finance data`,
        definition: `Techno economic parameters of electricity generation technologies. For each time step, each technology may have different parameters.`
    },
    IC: {
        title: `Existing and Committed Capacity in the System`,
        definition: `Values provided here are based on the user’s input data. Existing and committed capacities are those available at the beginning of the planning period and decommissioning schedule is decided by user`
    },
    AC: {
        title: `Additional Capacity Needed (without Reserve Capacity)`,
        definition: `Annual values of additional new capacity for each technology and each year by considering existing and committed capacity profiles, electricity demand, structure of electricity generation and capacity factor values as provided by the user. This value does not consider needed Reserve Capacity`
    },
    RC: {
        title: `Reserve Capacity`,
        definition: `Amount of additional Reserve Capacity in each year as required by the user inputs (user inputs are expressed as percentage above needed capacity)`
    },
    TIC: {
        title: `Additional Capacity needed (with Reserve Capacity)`,
        definition: `Total additional and Reserve capacity needs. `
    },
    INV: {
        title: `Investment Cost`,
        definition: `Total investment by technology and each year into additional capacity (including investments into Reserve Capacity). Values are expressed in user defined currency.`
    },
    EG: {
        title: `Electricity generation`,
        definition: `Electricity generation by technology/fuel and year as a result of user inputs (desired structure of electricity generation)`
    },
    LCOE: {
        title: `Levelized Cost of Electricity Generation`,
        definition: `LCOE is calculated for each technology and each year based on the user inputs (specific investment costs, capacity factor…). LCOE provides first degree estimate of competitiveness among technologies, based only on project related costs, i.e. without considering real operational circumstances and potential role of each technology in the system. Values are expressed in currency per MWh.`
    },
    AVGUC: {
        title: `Average Cost of Generation`,
        definition: `Average Cost of Generation is value calculated for each year by considering all costs that occur in the system in that year (e.g. annualized investment cost of additional and reserve capacities, FOM of total capacity, VOM of total generation, annual fuel costs, annual CO2 costs) and total generation in that year.`
    },
    CO2: {
        title: `CO2`,
        definition: `CO2 emissions. By default standard emission factors are used.`
    },
    SO2: {
        title: `SO2`,
        definition: `SO2 emissions. SO2 emission factors are defined by the user.`
    },
    NOX: {
        title: `NOX`,
        definition: `NOX emissions. NOX emission factors are defined by the user.`
    },
    PM: {
        title: `PM`,
        definition: `PM emissions. PM emission factors are defined by the user.`
    },
    CO2_S: {
        title: `CO2 system`,
        definition: `CO2 emissions by all energy consumers`
    },
    CO2_C: {
        title: `CO2 system cost`,
        definition: `CO2`
    },
    SIM: {
        title: `Simulation`,
        definition: `Hourly simulation`
    },
    REP: {
        title: `Report by Years`,
        definition: `Report by years`
    },
    Y: {
        title: `Year`,
        definition: `Yearly data`
    },
    M: {
        title: `Month`,
        definition: `Monthly data`
    },
    W: {
        title: `Week`,
        definition: `Weekly data`
    },
    D: {
        title: `Day`,
        definition: `Daily data`
    },
}
